### Project specific config ###
language: generic

# Get download link for latest ktlint release
before_install:
  - mkdir -p /tmp/ktlint
  - export PATH="$PATH:/tmp/ktlint/"
  - >-
      export KTLINT_DOWNLOAD_URL=$(
      curl -sSH "Authorization: token $GH_API_TOKEN"
      https://api.github.com/repos/pinterest/ktlint/releases/latest |
      jq -r '.assets[] | select(.name == "ktlint").browser_download_url')
  - echo "Downloading ktlint from $KTLINT_DOWNLOAD_URL"

# Download and install ktlint
install:
  - curl -sSLO $KTLINT_DOWNLOAD_URL
  - chmod u+x ktlint
  - mv ktlint /tmp/ktlint/
  - ktlint --version

env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

dist: xenial

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
    - libgconf-2-4
  homebrew:
    packages:
    - jq
