### Project specific config ###
language: generic

# On Linux, we need to download ktlint manually
# On macOS, we use Homebrew, which is configured at the very end of this file.
install:
  - >-
      if [ $TRAVIS_OS_NAME = linux ]
      then
        curl -sSLO $(curl -s https://api.github.com/repos/pinterest/ktlint/releases/latest | grep 'browser_download_url' | cut -d '"' -f 4 | grep 'ktlint$')
        chmod u+x ktlint
        mkdir -p /opt/ktlint
        mv ktlint /opt/ktlint/
        export PATH="$PATH:/opt/ktlint/"
      fi

env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
### Project specific addition ###
  homebrew:
    packages:
    - ktlint
    update: true
